# Generated by Django 3.2.6 on 2023-09-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branchwatchapp', '0003_auto_20230920_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybranch',
            old_name='Geom',
            new_name='Location',
        ),
    ]
