# Generated by Django 3.2.6 on 2023-09-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branchwatchapp', '0004_rename_geom_companybranch_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybranch',
            old_name='Location',
            new_name='Geom',
        ),
    ]
