# Generated by Django 3.2.6 on 2023-09-20 10:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branchwatchapp', '0005_rename_location_companybranch_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybranch',
            name='Geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
