# Generated by Django 3.2.6 on 2023-09-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branchwatchapp', '0006_alter_companybranch_geom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybranch',
            old_name='Branch_ID',
            new_name='BranchID',
        ),
    ]
