# Generated by Django 3.2.6 on 2023-09-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchwatchapp', '0007_rename_branch_id_companybranch_branchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybranch',
            name='BranchID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
