# Generated by Django 3.2.6 on 2023-09-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branchwatchapp', '0008_alter_companybranch_branchid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybranch',
            old_name='BranchID',
            new_name='Branch_ID',
        ),
    ]
