# Generated by Django 3.2.6 on 2023-09-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branchwatchapp', '0009_rename_branchid_companybranch_branch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybranch',
            old_name='Branch_specific_policies',
            new_name='Branch_Specific_Policies',
        ),
        migrations.RenameField(
            model_name='companybranch',
            old_name='Dropbox_Locations_carriers',
            new_name='Dropbox_Locations_Carriers',
        ),
    ]
