# Generated by Django 3.2.6 on 2023-09-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branchwatchapp', '0012_companybranch_time_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybranch',
            old_name='Time_Zone',
            new_name='time_zone',
        ),
    ]
