# Generated by Django 3.2.6 on 2023-09-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchwatchapp', '0013_rename_time_zone_companybranch_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybranch',
            name='Branch_Id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='companybranch',
            name='Branch_Name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companybranch',
            name='Phone',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companybranch',
            name='WareHouses',
            field=models.CharField(max_length=500),
        ),
    ]
