# Generated by Django 3.2.6 on 2023-09-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchwatchapp', '0014_auto_20230921_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybranch',
            name='Division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
