# Generated by Django 3.2.6 on 2023-09-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchwatchapp', '0017_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='Branch_Id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
