# Generated by Django 3.2.6 on 2023-09-29 07:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('branchwatchapp', '0018_alter_branch_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybranch',
            name='Branch_Info',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='companybranch',
            name='Branch_Specific_Policies',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='companybranch',
            name='Dropbox_Locations_Carriers',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='companybranch',
            name='Ordering_Instructions',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='companybranch',
            name='Other_Notes',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='companybranch',
            name='Shipping_Instructions',
            field=tinymce.models.HTMLField(),
        ),
    ]
