# Generated by Django 3.2.6 on 2023-10-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branchwatchapp', '0020_auto_20231002_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Company Branch Contact'},
        ),
        migrations.AlterModelOptions(
            name='companybranch',
            options={'verbose_name_plural': 'Company Branch Info'},
        ),
    ]
